pin pandas version to less than 3, add missing required packages, temporarily remove sorting of index in boxplot (#271)
* pin pandas version to less than 3

* separate codecov workflow in CI, add python 3.12, 3.13

* fix if check

* fix wheel package name

* add missing more-itertools to list of requirements

more-itertools is in setup.py

* add missing tqdm

* temporarily remove sorting of index in boxplot, so tests pass

Pandas error trying to sort columns, most are tuples, but one is a slice.
TypeError: '<' not supported between instances of 'tuple' and 'slice'